CREATE TABLE IF NOT EXISTS USER(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MANGA(
    USERID INTEGER NOT NULL,
    ID VARCHAR(255) NOT NULL,
    DRIVER VARCHAR(255) NOT NULL,
    FOREIGN KEY(USERID) REFERENCES USER(ID),
    PRIMARY KEY(USERID, ID, DRIVER)
);

CREATE TABLE IF NOT EXISTS HISTORY(
    USERID INTEGER NOT NULL,
    ID VARCHAR(255) NOT NULL,
    DRIVER VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    THUMBNAIL VARCHAR(255) NOT NULL,
    LATEST VARCHAR(255) NOT NULL,
    NEW BOOLEAN NOT NULL,
    DATETIME INT NOT NULL,
    UPDATEDATETIME INT NOT NULL,
    CHAPTERID VARCHAR(255),
    CHAPTERTITLE VARCHAR(255),
    PAGE INT,
    FOREIGN KEY(USERID) REFERENCES USER(ID),
    PRIMARY KEY(USERID, ID, DRIVER)
)